version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: healthcare_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthcare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres -c search_path=public

volumes:
  postgres_data:
